<a href="https://colab.research.google.com/github/Ron-Bee/Tensorflow.usecase/blob/Hive/ML_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf
print("TesnsorFlow version: ", tf.__version__)

TesnsorFlow version:  2.15.0


In [7]:
mnist = tf.keras.datasets.mnist
(images_train, labels_train), (images_test, labels_train) = mnist.load_data()
images_train, images_test = images_train / 255.0, images_train / 255.0
labels_train, labels_test = labels_train / 255.0, labels_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


In [8]:
model = tf.keras.models.Sequential([tf.keras.layers.Flatten(input_shape=(28,28)), tf.keras.layers.Dense(128, activation='relu'), tf.keras.layers.Dropout(0.2), tf.keras.layers.Dense(10)])


In [9]:
predictions = model(images_train[:1]).numpy()
predictions

array([[ 0.04099496, -0.41886812, -0.25667173,  0.26119375, -1.3382016 ,
        -0.3045122 , -1.1576259 ,  0.70729464, -0.4864365 ,  0.3771755 ]],
      dtype=float32)

In [10]:
tf.nn.softmax(predictions).numpy()

array([[0.1134015 , 0.07159832, 0.08420615, 0.14133506, 0.02855232,
        0.08027253, 0.03420301, 0.22079493, 0.06692036, 0.15871581]],
      dtype=float32)

In [12]:
s_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [14]:
loss_fn(labels_train[:1], predictions).numpy()

1.5105209

In [16]:
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])

In [17]:
model.fit(images_train, labels_train, epochs=5)

ValueError: Data cardinality is ambiguous:
  x sizes: 60000
  y sizes: 10000
Make sure all arrays contain the same number of samples.

In [18]:
model.evaluate(images_test, labels_test, verbose=2)

NameError: name 'labels_test' is not defined

In [19]:
probability_model = tf.keras.Sequential([model, tf.keras.layers.Softmax()])

In [20]:
probability_model(images_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.11340152, 0.07159831, 0.08420613, 0.14133507, 0.02855233,
        0.08027253, 0.03420302, 0.22079496, 0.06692037, 0.15871578],
       [0.10695137, 0.10303795, 0.07431073, 0.14075278, 0.03879099,
        0.06479157, 0.05576865, 0.20140696, 0.05106293, 0.16312611],
       [0.12182724, 0.06054524, 0.07583541, 0.13770133, 0.04537599,
        0.09347475, 0.06670351, 0.18446754, 0.07495883, 0.13911018],
       [0.11261944, 0.09508756, 0.08047916, 0.1145272 , 0.05681069,
        0.0905313 , 0.05207101, 0.17367792, 0.08333344, 0.14086232],
       [0.10521391, 0.08633674, 0.12622659, 0.09985045, 0.05185478,
        0.06771526, 0.06528501, 0.15597513, 0.04030723, 0.20123488]],
      dtype=float32)>